### PR TITLE
Allow MDX files to be used

### PR DESCRIPTION
**Pull request by cmdcolin**
Hi there,
I think that usage of this module in storybook results in mdx to not be used

I didn't verify this PR but I think that maybe by adding MDX to the extensions it would work

Was really a nice surprise to see a rescripts module with storybook since we are trying to use both of these things in our project so thank you :)

### CODE REVIEW

**Comment by cmdcolin** [comment]
Now that I try to test not sure this PR fixes it, but toggling on this add on definitely makes mdx stop loading

**Comment by Negan1911** [comment]
Hi @cmdcolin! it's weird but I haven't been receiving notifications for this repo, i'll take a look at this between today and tomorrow, thanks!

**Comment by cmdcolin** [comment]
Sure thing. I can try to send a reproducible case if you cant easily produce it. I could find that it worked when i had this repo off, and then turning it on it stopped working

**Comment by Negan1911** [comment]
Thanks for your PR @cmdcolin I'll release a new version soon!

**Comment by Negan1911** [comment]
Either way, I think that #2 has a more proper solution, i'll check that one in a couple of seconds

**Pull request merged**
